### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by koral--** [Commit451/Hyperion-Chuck#1]
If artifact is published to Maven Central then other libraries published there can depend on it. Moreover, there is no need to add jitpack repo to buildscript for users since either `mavenCentral()` or `jcenter()` (which contains everything from Maven Central) is usually already added.

Plugins like https://github.com/vanniktech/gradle-maven-publish-plugin can be used to simplify publishing.

**Comment by Jawnnypoo** [comment]
Sorry, no plans to do this.
