### ISSUE TITLE
Jitpack build is broken

### ISSUE THREAD

**Issue by auras** [Commit451/Hyperion-Chuck#2]

**Comment by kuFEAR** [comment]
Hi @Jawnnypoo, current 1.1.0 version can't be downloaded from jitpack.io can you fix this https://jitpack.io/com/github/Commit451/Hyperion-Chuck/1.1.0/build.log ?

**Comment by Jawnnypoo** [comment]
Fixed, 1.1.2. Thanks!

**Comment by kuFEAR** [comment]
Heh, It still use android.support from transitive deps(com.readystatesoftware.chuck:library:1.1.0)

**Comment by Jawnnypoo** [comment]
Urg. That is so annoying. Probably want to change over to Chucker as #3 states
